# -*- coding: utf-8 -*-
"""_init

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10TmnKx5c2Wfix_ZKQEUUUX-8ceL1GLTq
"""

#retinaface
#data
#_init.py
from wider_face import WiderFaceDetection, detection_collate
from data_augment import *
from config import *
from config1 import *

import os
os.chdir("/content/drive/My Drive/DLDatasets")
!ls

!cp "/content/align_faces.py" .

!cp "/content/config1.py" .

!cp "/content/config.py" .

!cp "/content/data_augment.py" .

!cp "/content/wider_face.py" .